prometheus-kafka-exporter:
  replicaCount: 2
  kafkaServer:
    - apache-kafka.kafka.svc.cluster.local:9092
  verbosity: 4
  prometheus:
    serviceMonitor:
      enabled: true
      namespace: monitoring
  sasl:
    enabled: true
    scram:
      enabled: true
      mechanism: plain
      secretName: kafka-credentials
