---
mariadb-operator:
  metrics:
    enabled: false
  webhook:
    enabled: true
    cert:
      certManager:
        enabled: false
  ha:
    enabled: true
  logLevel: INFO
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
