kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin
    ingress:
      enabled: true
      ingressClassName: cloudflare-tunnel
      hosts:
        - grafana-k8s-test.notyouraverage.dev
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
    service:
      type: LoadBalancer
      port: 9090
      targetPort: 9090
  alertmanager:
    service:
      type: LoadBalancer
  kubeEtcd:
    service:
      selector:
        component: etcd
