---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-timescaledb-17
  namespace: timescaledb
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: cnpg-timescaledb-17
    major: 17
  storage:
    storageClass: longhorn
    size: 10Gi
  walStorage:
    storageClass: longhorn
    size: 5Gi
  imagePullPolicy: IfNotPresent
  postgresUID: 70
  postgresGID: 70