---
# Source: spring-boot-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-data-processor
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: kafka-data-processor
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-data-processor
      app.kubernetes.io/instance: release
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        helm.sh/chart: spring-boot-app-0.0.1
        app.kubernetes.io/name: kafka-data-processor
        app.kubernetes.io/instance: release
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: spring-projects-registry-secret
      serviceAccountName: kafka-data-processor
      securityContext:
        {}
      containers:
        - name: kafka-data-processor
          securityContext:
            {}
          image: "registry.gitlab.notyouraverage.dev/spring-projects/spring-boot-kafka-processor:3593fd77"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {}
          env:
            - name: GRPC_NAME_SERVICE_ENDPOINT
              value: grpc-stats-aggregator-service.spring-projects.svc.cluster.local:8080
            - name: KAFKA_SASL_JAAS_CONFIG
              value: org.apache.kafka.common.security.plain.PlainLoginModule required username=kafka-user password=cBDq5ftC2xyESqI2T1lhRCSjGcaeLZg1kmT5CA8hA8Ll4STUZ8d9lzM5ILxdcsCH;
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: apache-kafka.kafka.svc.cluster.local:9092
            - name: ENABLE_VIRTUAL_THREADS
              value: "true"
            - name: ENABLE_TRACES
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: TRACES_SAMPLING_RATE
              value: "0.0"
            - name: OLTP_TRACING_ENDPOINT
              value: http://locahost
            - name: KAFKA_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KAFKA_AUTH_USERNAME
                  name: kafka-data-processor-secrets
            - name: KAFKA_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_AUTH_PASSWORD
                  name: kafka-data-processor-secrets
