---
# Source: spring-boot-app/templates/sealed-secret.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-data-processor-secrets
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: kafka-data-processor
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
spec:
  encryptedData:
      KAFKA_AUTH_PASSWORD: "AgCf5cXako6SDZtdpM2lBZrFE+tyXCC4wY8G14dqAYw+WnviHUGrlxhCxq7EXyQ7DOxG3KfgauWs7gtWkOs9NACbXEdi9OVFT2WFAW/zZnH0sl2Bht59KYY+jhWHYwhmugSTqvpKdm/3hYzamQW57E9m7KLabSTd5pBwxXck7aonDlA1VPNnGzmMadse4hwdm/ba11PuQS9mHGfeGZcuBr5iR+ONRvSrYBAXNDds4JzTWsUdoEEWa8SWK75rDWA4J+sN3YB0azdXLa0dL3wy9S90mR7hYdgPT7u8knnjDOxqkb69cONELTFP1RT65kIhMKgA6EN66PUIgkgZDt+/6iGqhnTP4RhhRKcqL40MYf2inHO0aAD8MJ7DqjDaNyYweITD9vZQruc9/Cl8AZ7KxSIzP1fnwQ/2kQIlXIYWFX5cIL+qlgO0X29layDVelLkQ84vEtntiyGZc6t8DXY2KmVWNDu9tTJhdfPxho05heKfJO8bv/iQA9X19bIg1VZtHyPwUx3IAF5zE5TTAD2clybkqdje5JRnEZqb79b7Wf6AETaRJh7Mi/TM8IdVYqb5uOMp5B0ulO1FwgbEtz4Y35hhBFuPPSVtXjgwL43tGNtBsaOBFYCWPUuIem+q7xXEhe4BXvWfadnisEeMEKqfca6WCVM8ommE2pjphGOQ64OhGjvuI3zyGd7rhsaQqgX9wlqc0PnkdIuW+L0htK7oP9ak1ObZSUvkDeyCzXTGVkbnqbvmkFPBXyLLufjsWblmMOqDEqvBFX6xA2RbLbIAqHZn"
      KAFKA_AUTH_USERNAME: "AgCEupFC2Bl6EQ8jzE4FIRqkuA+tdb7FcfXErSYwi8zUFvZFJDuhyfX7unFiyClDtC16K6H7rLCG8FAQWsXWYul20wTH9PE7Sd2OSzDn1fXsco7hcOMNyKhzFcjqfaEVvxN/6HINSg5Ae5JfrNZL+xkPFUe0K3E3A47sfZ+vODssJW9lV5cGty09Hxxfw0gWlvbqKKuBxB2lPmwZWhNUD51p2y0E4cBSdeOgEjs1OFvpn8s3IB9r+jcax8MNzQbkSoU770OsWtyQoFM6447NxB722pYDVH/zq/knIQvEAOYnqGpbIR5lz+e3Rj35LnK3+uDA2FE0XjSk6WH3/cGU+p0tRtI0Bt44UD3YHRJfvTwpx8IuewfmaS6uDILS/5nPx+7DpxwnErQs2SLzZl4wjN/hv+K0jLIpJaRFzyB3/rmisHQY+cGeVgorVAfjJ0N994H6lvwaNfI2qPLRwMdznWEPetODGOu2595gk46H61igBmRx9rYaQKu75FxM66vDz9wKqV+rxh6HhE2tnDD5eREP1s0TeD9acOTdaqDWekEXHtQ2qRDmbM8zNY4JtA507IPIkDvl+yhOjD7tvBPO5I5CsIbBLZBmzTfn82f9Ob3O0FeeMIncD8oAO0leVayf83GM5Id7nA2NhIgXTy5M+MmJIlWmo693Mm/+FvSD71BXMEf033ESqjwOeGHXMKFdfFY/7/CYEfGoTYih"
  template:
    metadata:
      name: kafka-data-processor-secrets
      namespace: spring-projects
    type: Opaque
