---
# Source: spring-boot-app/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-data-processor
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: kafka-data-processor
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
automountServiceAccountToken: true
