---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  namespace: calico-monitoring
  labels:
    app: prometheus-pod
    role: monitoring
spec:
  nodeSelector:
    kubernetes.io/os: linux
  serviceAccountName: calico-prometheus-user
  containers:
    - name: prometheus-pod
      image: prom/prometheus
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      ports:
        - containerPort: 9090
  volumes:
    - name: config-volume
      configMap:
        name: prometheus-config
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana-pod
  namespace: calico-monitoring
  labels:
    app: grafana-pod
    role: monitoring
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - name: grafana-pod
      image: grafana/grafana:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-volume
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-storage-volume
          mountPath: /var/lib/grafana
      ports:
        - containerPort: 3000
  volumes:
    - name: grafana-storage-volume
      emptyDir: { }
    - name: grafana-config-volume
      configMap:
        name: grafana-config
    - name: grafana-dashboards-volume
      configMap:
        name: grafana-dashboards-config
