---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-dashboard-svc
  namespace: calico-monitoring
spec:
  selector:
    app: prometheus-pod
    role: monitoring
  ports:
    - port: 9090
      targetPort: 9090
---
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-dashboard-svc
  namespace: calico-monitoring
spec:
  selector:
    app: grafana-pod
    role: monitoring
  ports:
    - port: 3000
      targetPort: 3000
