---
# Source: spring-boot-app/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grpc-stats-aggregator

namespace: spring-projects

resources:
  - sealed-secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
