---
# Source: spring-boot-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-stats-aggregator
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: grpc-stats-aggregator
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
automountServiceAccountToken: true
