kube-prometheus-stack:
  grafana:
    adminUser: admin
    adminPassword: admin
  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  alertmanager:
    service:
      type: LoadBalancer
  kubeEtcd:
    service:
      selector:
        component: etcd
