mongodb:
  namespace: mongodb
  architecture: replicaset
  auth:
    existingSecret: "mongodb-secrets"
    usernames:
      - admin
    databases:
      - admin
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "longhorn"
  replicaCount: 3
