mongodb:
  namespace: minio-operator
  architecture: replicaset
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  automountServiceAccountToken: true
  rbac:
    create: true
  auth:
    existingSecret: "mongodb-secrets"
    usernames:
      - admin
    databases:
      - admin
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "longhorn"
  replicaCount: 3
