apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-test
spec:
  project: zeus-kubernetes
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: ">=2.17.1"
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets-test
      valueFiles:
        - 02-values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
