sealed-secrets:
  fullnameOverride: sealed-secrets-controller
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 150m
  metrics:
    serviceMonitor:
      enabled: false
  pdb:
    create: true
    minAvailable: 1
