---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-creds
  namespace: default
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDBjLGRkOwKrhxRrpg88c56tQzYYNIjLn3Ggfhj0hhD0RC2duQZyrEkjohXKoKbN+ZTV1B+09FvWKwQXmwMD6qJdB7MHIkiBQMJT0Ow7TLHeGLxagYLcmWZygKl/36YdAlFDA4ySym0qSowfo6AJNZ9Q/ZhRPzj5pNwMjGlWSewt2UEz3uqFPYh7QFUp3LPNM9IJTf2/0cC+bS4nydcuhbCJdV2I4j4/vizpcgUP6IjczXA5e77E0M4LZbAB/jb5yARW5ABpGh3t907bBrg6sVMsXsgJoiZcCkP/ZOcth7LHeEdxnEJ5H3FLoDFH+ryc8b/fvMiOTrtGQqleSwdU+rzhJOXYqAwNqo95Bj7j+9NJBPfXbGhyUywLhUXxBsRytIDwNRMHaY+p6m2MvU/4Zh2LR4jyIkgAQ8QtzChDI3OfGv1GlTHwv7uz0bIVmpacQFNE3Ln6xEnWIigDFP7Y4CjwkyLTbwR2T7W3CTOB9CEkzWihY6vsn1zVSQeQdurlsRpJPcV3jv2xjAxu9CQ105GrA9b6p2qklouZ0/sPyHCj07JoYE2kuffDm6jR0ySLZ9rWWsM6uCYdJQma0HwUMIQ/kHxSVhCkWmUEKhKygmpJ4fmIwzBuzAhwI3QEUj8mC7u8sCdiCJGyQFQaDZU1Sx5p3RY7jJoImmBdGbzwZnhEuoAFhmLg3Rw4jVz9UwCDJ8XJGul5pfEfmE/D1cbnx1J2eMKheCZif0h+l2ujg==
    ACCESS_SECRET_KEY: AgBtMPxEWRgAV7Mr9SEMH0cftPz9ds4TFOpZhMRosVST4MsIbtqvS/kn3kciHuHAs8zh0QIO00Uwp08oKAGd1d1SCpu4SpyrfLyUncoTGNWwyTqI5S/kcH5AHb5MPkRoEDtwnZpkFCsCzqj4mwbSdXIFgEVWpEOOSCMcb3Zn3rkz6NSOYLEaQxytnmos25j4oz7P+/9NDz0xU8QjNbcr1jEovvJa0Ikorzmxbb8PCskbOkfsumbaQO9Kwlar4yRU+glRRHOG0WFkht7HMlGjH4sAN92dh2B4vBdhZ7NDJNZL0VkUVQQIpb9nCnPvf2AIOvv6WZ9AnbI5yhy/NOCppF7+jXW9SUqpOoE2G0DZRmaTFVGKDfyEk9KT91CdfJ6gKT3B3yfr52pdIcvjxBTpAXiTPRzjGpQKNv3rwRJsgHfoXaSBM3frmsXgYarTkV4J2sBH6R1SK8po7yFeSTH2n1TgCi5jXyd/BCfTHbhdFJRbLuPukBu5cC1I+l9X3serg+5NEVfYr9I9DB8XL4XBndTp3Xr4baMcTNvR3s4hAMOLa3Zs/xpUwxzgnq61CGGfnT61dvtaTly8ThDRi3uCMDRG5O5tWkzH4uFmGAaMRzLuqHKS6EhZAJxMwc0djxYXKOwR8Z7ZgQKnnDcxAjk8VGoGfwFN7es73frpGoNn69GhM1+8i46MfShKQMf7zKRxkLd3QrZ1U++naMszQfIuEviLZvg8BTmIE/hSMtOu0A==
  template:
    metadata:
      name: aws-creds
      namespace: default
    type: Opaque
