---
# Bytebase database role credentials, consumed by CNPG `managed.roles[]`
# in postgres-17 cluster to provision the `bytebase` PG role.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bytebase-pg-creds
  namespace: postgres
spec:
  encryptedData:
    password: AgAOzTd6ZebPgNMQTbhTniuVe5xqSKXEnagUmpF2Fl/0RNQZ/HCTCYaZFHXy5i0hzxP9r3BmOQCuQypilqZmkNsxzE15+pa/g02rXAvvDLAMmy/5j96oPai4JzuR3KhsNj+egc00lZLARwABh3bZyT1UKVL/sSz6cR+LlLte/vFguM3GgEsY6fcLZVp30kE52sruOT2K+UFP0F9XXoSWrxZTaXkgkuETC1n8jNDvHUX89jQjAYRoI6nVl6bbAxYZ6xwl3qS8YoZvCW/sxruu0rkcU9O7vsJqHUTMfKHTx9BsNbizpEQWiBYdks5qP42Bpm5xuTnKhyW8fr87+eX/GunwEZ08PDgUOzKiQQr4ii8lLGL7l6F1F5lQ3Y1oCnq6+O1Uob/rDJBOt0wIwZkl7uptsSeWZ7+YgjEKpmsEw2IKJnWA4UuaYE4liO75aXBsaajzk59RBqa0htaOA1+OnRHdQS8epSiSV3IJ0ey6NbHl+ieg+ShhHqvIUWuJKb7vSGBjKVpuq6w3xft0b4sBgGagfAVLh+Zrip7fBz8SaK5Q9iHFHWhqUsOMqe58eXIe5ugMpDZR6q6cmnsbucw1ZtA/9Lyfn7hecBMqjsNWcd3NeFdRvEyf4HWnDlh14kgmkmB1XLGvhV6UyAFC9wUiP1USu+csjSseli87R6vUvY4CmUykdg8zaK4a358JTwMRH7NNC5W3RhQAZQ9UvU/xBA8+WxGVtGhSUgJffyd+4/q9jQ==
    username: AgAEUSjljCH2hUfyebWT5QNMfj+xJAbO6xuTT42KRhr9kO+O2X13gNwMJxE3aI1AozH3x/S+VIxLlYuPn5yDBlwIAITVfiko4OYzS8gghCxOJ/YV1Bm+4wQwmU10hqh2PRAbQNOJu6JeMnV6zOzvUzFegmDQrRA4mv3p1v1SumDHeuRlJ1QQfZwC5F2xIXMvHw2YUAXsVXgm42kojuSdf30VqXukPjQli+HgE1Czn/ufqhPX0qYzmTO72yu29+uummhoe+LGvXxHr+vGgDoyT4tXc53p1WAgmejsmFzCscuJDtRetOusQWA/Nuu/0azTyYuDPUh8JZWLgSBYcdTUc1x51EgekA3p35i9kNiSoYWNoFenvtt7mrS04bQQ0a2nNhBAZnlhkIpg4bFd9ZBa3+RK+eZxf6DONvFiPb6+RRqbJYH5vTSBK244cV2WJd3/RJHVM29W5GSRpnjYFMd+v0KUpS6/SxM2YcD6memXuQdoTUjH1RvJlyaXSGVBvvpv0ues2k7ZWa21i9FkoxJnbE63zCiOo0K9HRJSscgJR1dKMaiFs6yVvelBg3l21b6MreelVCw+6SUH3A3EusG86TM6YezTI3LNhkXIuhUQLvwIxAKA+9pimbaiJXiU9YAdN+JA+aYBt5X3PEYs+xAlTbefGKHQ6egrD0Ot4brHHOmKWRJA4gAy823UxP488awP+OluKk5sebCoeA==
  template:
    metadata:
      name: bytebase-pg-creds
      namespace: postgres
    type: kubernetes.io/basic-auth
