---
# Full Postgres DSN consumed by the Bytebase Helm chart via
# `bytebase.option.externalPg.existingPgURLSecret`. Key: PG_URL.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bytebase-pg-url
  namespace: bytebase
spec:
  encryptedData:
    PG_URL: AgB9KcRAByjozqBLjGFWbanmRr0sFmxlAFpQ6g1rWNZvuAfZbWotoDY5mvIrIVX5NHFKvcOUkE04ITr3CEAzB7f6O5u2chqyUiiWZIPDA841GZPxEAcX7mtHrhGniowxpSEM/A7u8RzHn8LUJngnBTywjE5cyfqy8Lti5x8VisN8+V7t/+ImeQav7S4zpfqZ/bOjfWS7JmqbWzmTKBOfU/geG8+yUT0Wh+1gN8r3kuF3eBJvssEdqqo2FmVKia173eIPVq+xnpffbaV2qN1aKBn3tu2EXrvvRHtD/5n36TVyOoZV2QJxlkyy1kYXqafwzEgUALG6dZia/Tv/5X8ApNyONkytF2iSnj5u9qWshf9rRckDX5d2qKOPY4KxNjEVXqCx9xbVNun6b9ajasEQEMJbEB45Xu6eGzX1jxD9t0uUvuS4wf3x7fKebmG6MZlQPRQq1cYo1LUIhTep6QvhCNxRStmMJ/wD1hyAyjyneACBylbacrFeAfkwzkMprZk9n2TGxULdE/vsOcj80P61t1SEgRZcbiJMpS0Sd3L/UdY0xJVvbmwYfdiDLkXgvUG0+qsrvMARW3tDFHQJYs6ahkuEHQZdAOLu7FZudTJqmWZ4tujQaOwm98UODv7vDDo17ekfL3/2rQNCpAK19Wv9SB3rZlztegtYSA3h5nAR1FdvAFWhG8JnKJbetXK5Z92VN4iVPpOrr5d8JoWeH4EGPLhs7bPlI9nra82xlCZT6liNpoeJttmw3rhDctYyX9npy2kENzVzgKIm+9hCHxDK/hBlniVS0HtC9bS5l47wE0WXcXwvtC3OEPfoxKzUbkhAoFwRus3B4IC1R9woMQ5hytzRBw==
  template:
    metadata:
      name: bytebase-pg-url
      namespace: bytebase
