---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-mixpost-credentials
  namespace: mariadb
spec:
  encryptedData:
    mixpost-password: AgBWe29jO79LfuPHZJphCXXP5XS+PnD6RrKfulJ0FxaI06fA0Yr2x0bBC6Yj1lCHOGLnJ3gRqjn0m8CI1RLRedXlZyG45uS7pAJ9Az7iZKZfkyFGHBzrg4D8C10JmqKofOIxb4CjhM/D6rDHG3ducoZ84Ez8OrmQb3uCfH6/qrpno/PvIY8rS69HIkSIxIKrgYyG2QwY59XpDGhXEYVe8fbafnDl39dCXLufeZonzBot2C8pHX+aGwQwBYnYqsJQ3NbnBPzxdYS//zsb7zquK0KvNl2YEJ+YkJ8uQnOYES+zaQTq9j8apbKIzitrdF7L3lXJW3zn4asGEoFIDgpXj7DW8f7w2u4khjzm+aPmGHo/ncMEPhRezAhwVZ1A17CZap2M1zge3G79zyv+9wTQaw4f51mkotxueBtrnOgsDwtr9Q/1G+FMODmpoOdXztG8OdTDG4ZlDIMjwskRH5SGNNPs1IVCu2vAKWDzZ95cn1q3tM8TvIt9uG8yaW0rwtdYSAN61bASROE540JIZZmldjR9EyfvFl9ntyqiGda5nYcaJigH89Ube7Tv77PDbYKNvGhHNKwQafNzUOE8jG0vtTmT/dP4ea07fFcYEXGuSvSMiqN6kk/RQeGHZ9mDCxLDrfFuJEGWo6RyRx2tEg5i4bWlzc9bl18VRDhTfM2Se4mcfPyvzmmslKy7lFS6Z3CpxhQUIEPyuhP06Dmh1hxeQMfLI5EIcz5RDzEWSWfvkH89e63UPvZMfuLBiYXj3A==
    root-password: AgAD/tNI/aF0bryqBtQILFc7cG6PypUbQt6RCwYRHesHiHaOumZi/yV0qLcYqUCXZRWyJyV2rSg7iCxfjZNW/ixs0p/+fMD0/N7zigVvSff12O7yb8mSYF9T3TPbBMsG9gVLOL7EOiLYh4BPS2lIrjKjZbWhqPCcEDqkfXDeYF9LpOG2PfOViEnUS3oAYXgOOgEQ464obhn9HJxNW9Kwgn2Cb9+lEPlOwn67Vbv4OP8iJtHhat6cdMlvngKdD86RLSlx6d7aPysdudcHq9H9XbmPl6oET/2xY2kFqMSDAw9L/dH+o/qNVT2v58Cv7JfP+O+UbMZ0xE5olxvPrU9LVNmO95b4U3zGfeeBrPpxramSLYs5tPhIH37/9fGwHlSVUO/jA4nnVym4HqqCvIRGvebaBAwKB44L97u4nZQPY/+Uk36CMRUf2uRCyxOez4bsOqsNyJHhUtohevQMqKBmnVTaWeut/84Oiut2VU4SXAdbJjsNMZoiJaCTyZnFJakj3ADder4naC38FgeMOmxELgiatZ/cbz71W3vTdHaOnipCrStKewLt4YvUsEW7Zy9ZW+7StXfBuTBbvrdsnXe+kBgllCJj3wv/xbvmcg1A3RQFQLlJ/RvPTVqrkHeDs2SEs53KCx+WRHGae23FAJA+27Z9KcWC/cEJrRp7xCxloHgxkKkumectTxPR+9huJzWsr1wA5yV5pHE8s3p8XKyRLYS12FFdpguxKHAPC1b/X4f+f3PEdgf7DoXPVb7Dvg==
  template:
    metadata:
      name: mariadb-mixpost-credentials
      namespace: mariadb
    type: Opaque
