---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-env-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgBGD4j+wvcR+3UzMUWNifDnJCKU/nz7XuYNCx9Udh7U0JXz4hzYoJZELaMUOF2T/sc4edUV3rIN6uaHRYhKbdo0klZV6rxM7ZNgCoAwH/hmypZyT5yJ46mGbinS31LNSM4l1Wq36NR4De8tMlndadkLb0T8lyHNzc364B8YdEoa0PvANm2suZCzM9ennfH3S7m6oTikDITvEspmtAxWRtNvrpl8iSoEEzmgKre3g1dKnDWCg2zICMXLNoTRnPYXbvpGO9UxT21ch84xNXQ7iEuvfHbXydSd9hY+11nb/FM/6ooZrfwf05x/OWVfvEP6g3rDKmbypNhQgb4XC3ZPlJ928kbBM4ciVJF9sxgwHtxuYLepYSjb/zoEmuh8h6MOpkXY2FnfcsjHdezEw61DIauIu+/g9RKXWWjyZ5+J8Cr/FXZ2nBSWbjuqRo1U0estgmjkSE9cU7OSc5zsMetUwSV8D89XoftNaeILFTKi6f6BhfgdVwiTUvmtOuINAs9R54+o6ErawoIBYjsg+bu38olqngrQSTSJHnDyi4nuugur/1u6pGmNenmHhEkMVJQoccDAlhsOqdMFLTtN7X9wituutlJOdN4Ta2kEbkBLeziKlEN6jm91XKBcK1JAnEis1UFx/z9CEo2KER3keq2Jj2xT1O4i4AxB24u07XBz15YrtClsOlkX5537c+wMcCXG12TQ+T9lDVLJNFAjOI8pNy6QKCvcN2/MOQcK065yzloJrViCAGxflCCTOv+3fLvN6wItZM/Qo5L3JsYlM/cVOYLccqqcHPTgDmKBloqPciEa4QuvSrSJXE9KcylFFJV5bA9kHerONg==
  template:
    metadata:
      name: minio-env-configuration
      namespace: minio
    type: Opaque
