---
# ClickHouse `opik` user password, consumed by the Opik backend chart
# via envFrom. Must match the password_sha256_hex declared in
# zeus-k8s/databases/clickhouse/cluster.yml `extraUsersConfig`.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opik-clickhouse-creds
  namespace: opik
spec:
  encryptedData:
    ANALYTICS_DB_MIGRATIONS_PASS: AgAbqJXKrydUzNNo0u0/oGCl+Ybz1tEFD+mTaTmt2oiqZIfrdq9J+VcH79SA5mdCl+g8/bWv2E4WNYfD67iET7WfrHobnLDaJxUqL8FKYnAllFGQXPEAuDgbUW/J/nZI2VfVaqJApeLT/Th6H5opUNNITpMMFs85Rfo6+miIer1KPI3JVJCH2tJbXVOLlsSFz++j3uoQSfh/UhGkig28d0ncJ42puCyWqjC5PQxu6mR5u+ZiPY23sHZauViAKuaAHVWocpjJ5MMy5KQJVhocHyoW0yDQ0XqPmB9jUjVqzRF6kHMqYF7aDs9uUMFzP2q5x4Prdn8WkxyiWUMunhT1wdlGm8zBKZ8joYszfd9IAfvwETjAYjboapmmS9ziHiD3DrnBQiVIQETC4ppG91xEq4itN6qSF1/f2x7DWBNT34bNIXnE0B18nqN7nqROpjGKDY4dFhXkrox1dkfsbPqlJ2QlKMlZ2/i4uK8QFvk0nB+3sR8iRgp2QHayesTxQUXwqyT00X3u0K+6/0Q+nJHHXuE0FyV5oRQ+xNMsNr+heZqMZynjgM9tE2zCDE42WGZ0P7ha0neWhawAS4zC0qa2Be3bOn9ySl1262xJnW6ZW2sBDqiN9wHreaKNcE/EUzN28KVSBUpmJqfkoJjm3tsdGqZcYYdlHOqBLn7EwhjrO7LKu8rG0U4mXycNHRQsr4MMK8NKSy01MJfL1YpPrcol+J9ARyHwncY1IymZhGT98dWjuA==
    ANALYTICS_DB_PASS: AgBduWOGM82fi5KyxlzTi1W/czJnBYrvCIkNiKdqXT4QHkAJ34ROFStJEKdgnzMaNtoHBVQIGrLqTHsIZ/VlQP0ytceMX6q38sjoXO3j8b3mBoq8ZFXJXr+NKny2/OTYhBYaXdMCsnvqUUcXZzFgG0BiAKIvV+bWSsoZffFPBUEmY4w67mC3bryuy3rprn5lVxo9a5AJcPuvZJZuNeITnESWwGX4HsnNEfFFYE4XTCBshjBTb1nY2/0dpVObMgkvz7kMfCKbRSnJZI8KvjlNVhqFcfMvpWzLDgJS5qyS9Vqb9/l8R9UThYbA13+gWd2S+n4/Y83UrCnvotuN0dI0YlrFft0E/pxAaXOgJjYlLWfUlsz9xzJ4GHL5+Pe4lGbf8AkIhKvMkr48WN0BAbJjwR8d18+g1cxbcnxMC62g8zowCtyKHlYFDg5yTqldNaAE/C7U4kjL9BtovjauHxYvIgOCXB9dEvGFdV6Qc8APfsheMAz53McDGIV2DpZ3SLFyZptNDcCI3JD/nfqVKI2vU04sKPFPox7DQMP62Icg53VJUAgthuvVYsVADHm3NQQoR71z7fx84ygFpm1qEOPdhBPLmj8H5l5n5X9xHlyQs6crdI4fCVfuuN8WPZP5EbtWnEXXi3R5mL4PVHwtcrecpIrd1eSixW6oYKrFve90QIuRyepaB29onjEGLJdhpOyIxqCqFpTl8AfAaIkjQLHqPpmAX3RifbglTpaPBaO0reCeew==
  template:
    metadata:
      name: opik-clickhouse-creds
      namespace: opik
