---
apiVersion: v2
name: confluent-operator
description: Sub-chart for confluent-operator
type: application
version: 1.0.0
appVersion: 0.1263.8
dependencies:
  - name: confluent-for-kubernetes
    version: 0.1263.8
    repository: https://packages.confluent.io/helm
