---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner-nyad
  namespace: gitlab-runner-nyad
spec:
  releaseName: gitlab-runner-nyad
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: ">=0.71.0"
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-runner-values
