---
gitlab-runner:
  replicas: 20
  revisionHistoryLimit: 3
  gitlabUrl: "https://gitlab.notyouraverage.dev/"
  concurrent: 20
  runners:
    config: |
      [[runners]]
        executor = "kubernetes"
        [runners.kubernetes]
          namespace = "gitlab-runner-nyad"
          privileged = true
          memory_request = "500Mi"
          memory_limit_overwrite_max_allowed = "5Gi"
          memory_request_overwrite_max_allowed = "5Gi"
          memory_limit = "500Mi"
          poll_timeout = 3600
        [[runners.kubernetes.volumes.empty_dir]]
          name = "docker-certs"
          mount_path = "/certs/client"
          medium = "Memory"
    name: "gitlab-runner-nyad"
    secret: "gitlab-runner-token"
  rbac:
    create: true
  podAnnotations:
    linkerd.io/inject: enabled
  extraEnv:
    CACHE_SHARED: true
    CACHE_TYPE: s3
    CACHE_MAX_UPLOADED_ARCHIVE_SIZE: 2147483648
    CACHE_S3_BUCKET_LOCATION: us-east-1
    CACHE_S3_BUCKET_NAME: gitlab-runner-caches
    CACHE_S3_SERVER_ADDRESS: s3.k8s.notyouraverage.dev
  extraEnvFrom:
    CACHE_S3_ACCESS_KEY:
      secretKeyRef:
        name: gitlab-runner-s3-cache-aws-creds
        key: accesskey
    CACHE_S3_SECRET_KEY:
      secretKeyRef:
        name: gitlab-runner-s3-cache-aws-creds
        key: secretkey
