---
# Source: spring-boot-app/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: plg-service-scheduler

namespace: plg-services

resources:
  - sealed-secret.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
