---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
    app.kubernetes.io/managed-by: argocd-gitops-repo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: zeus-kubernetes
  source:
    repoURL: ssh://git@gitlab.notyouraverage.dev:8443/a.anand.91119/argocd-gitops.git
    targetRevision: HEAD
    path: zeus-k8s/operators/clickhouse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
