apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '25'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argocd-gitops-repo
  name: gitlab-runners-saas-nm
  namespace: argocd
spec:
  destination:
    namespace: gitlab-runner-saas-nm
    server: https://kubernetes.default.svc
  project: zeus-kubernetes
  source:
    helm:
      valueFiles:
        - gitlab-runner-values.yaml
    path: zeus-k8s/gitlab-runners/saas-nm
    repoURL: ssh://git@gitlab.notyouraverage.dev:8443/a.anand.91119/argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
