apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-15'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argocd-gitops-repo
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: zeus-kubernetes
  source:
    helm:
      valueFiles:
        - values.yaml
    path: zeus-k8s/kedas
    repoURL: ssh://git@gitlab.notyouraverage.dev:8443/a.anand.91119/argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
