---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    app.kubernetes.io/managed-by: argocd-gitops-repo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: newt
    server: https://kubernetes.default.svc
  project: zeus-kubernetes
  source:
    path: zeus-k8s/newt
    repoURL: ssh://git@gitlab.notyouraverage.dev:8443/a.anand.91119/argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
