---
apiVersion: v2
name: keda
description: Sub-chart for KEDAS
type: application
version: 1.0.0
appVersion: 2.16.1
dependencies:
  - name: keda
    version: 2.16.1
    repository: https://kedacore.github.io/charts
