---
apiVersion: v2
name: minio-operator
description: Sub-chart for minio-operator
type: application
version: 1.0.0
appVersion: 7.0.1
dependencies:
  - name: operator
    version: 7.0.1
    repository: https://operator.min.io
