minio-operator:
  namespace: minio-operator
  ###
  # Root key for Operator Helm Chart
  operator:
    ###
    # An array of environment variables to pass to the Operator deployment.
    # Pass an empty array to start Operator with defaults.
    #
    # For example:
    #
    # .. code-block:: yaml
    #
    #    env:
    #    - name: CLUSTER_DOMAIN
    #      value: "cluster.domain"
    #    - name: WATCHED_NAMESPACE
    #      value: ""
    #    - name: MINIO_OPERATOR_RUNTIME
    #      value: "OpenShift"
    #
    # See `Operator environment variables <https://github.com/minio/operator/blob/master/docs/env-variables.md>`__ for a list of all supported values.
    env:
      - name: OPERATOR_STS_ENABLED
        value: "on"
    ###
    # The number of Operator pods to deploy.
    # Higher values increase availability in the event of worker node failures.
    #
    # The cluster must have sufficient number of available worker nodes to fulfill the request.
    # Operator pods deploy with pod anti-affinity by default, preventing Kubernetes from scheduling multiple pods onto a single Worker node.
    replicaCount: 3
    ###
    #
    # The `Pod Priority <https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/>`__ to assign to Operator pods.
    priorityClassName: ""
    ###
    #
    # The `Requests or Limits <https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/>`__ for resources to associate to Operator pods.
    #
    # These settings can control the minimum and maximum resources requested for each pod.
    # If no worker nodes can meet the specified requests, the Operator may fail to deploy.
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 500Mi
