minio-operator:
  namespace: minio-operator
  operator:
    env:
      - name: OPERATOR_STS_ENABLED
        value: "on"
    replicaCount: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
        ephemeral-storage: 500Mi
