---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: timescaledb-secrets
  namespace: timescaledb
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA5oh31+HfxSYald+rRNCkocbyPkXTX7Zt4sycvXAb13s+WzXbdAy+x0S8OV8KsMJNYN9PswUlrklEvkXlGUfa5PHVe2zgOxJPOD5osAiVW9j65Astz65LyoAQmHVgkYxr6QuZcb1mPZv5TMl3HikVx/NBDHrbwjjnMenH7mUTeh+LHbUHvTXw5it2h4bHqi9h10j+OzvFhEuD0/0L7IYNStpFEmWmoA9+Dg2JRXvgoftbIUt93q7nr47XB7wDiqgTmsmX05cfT0Flmc47Eyg6qKNaSVR5s/mPj9haJUQcz1vBuVbFtIqoZSzBLs3G2LLJ1RT+M5yrFqGZ9k291tqTKFQ8Xh20xbi2dFJ8A1SW4dGu4ReHu+tEctZqUqZbe1ji5HuSYLasTM6Mc/ektiBK+SkOKYQZ/tac3dFN31gLiwizLfLb0rmK85gZkdJCeLhgDgSHwCMAP7EFCkmZ5yCfjJK4a8aM9xEzN1Gy2AA+HsA7U/ALzDkOtIRQGKGY7AayOqOftGs8kBC/xNfE0kbcr2rOm5zNYnDZ+Zv1AgGfQ/4K8RbzSFMFDmHn10H3Glob8vkYb2656MhgXRDRGJmGZ2ELdC8B0hHondt29lXORVxEL2NejFNADm2pgGQs+Qd+Ihqfc64vKKxCLLzhpOZDOzO6fYL33/awwQAxyF2N6PH3x1S187VVC3ZgLQkX4v+YeXpOBcfCgvsrTEeKDXqnF8CXtdqhoErO2Wukb3ipCH/WjGCt2Qpe68Arq1f7acaDn4f+JyQ44D+AVHQ+md7Sb
    POSTGRES_USER: AgCnE7VHdHLuhu43cC9tST+m3efxDZ7pa4tVzwa6CmCx7r3T1ZTQlNFUP6ZZlS9VHQHEQfkL3eICzvUJZpppAMMxGWk6GPIpv+F4hg6CybqqidaiMq2ZwEPwOzJGLkyqpH8sHXcl6GzgJ9jZ5C7m/H8nlq8IHaPUgUdtwOzCBSwiPX4klgzDIwHZHNFFIyQuPGmAB72IXLt7f9yK8mPwcNzXkh6VzQUubKBWdhwCU9CGCIsYJtrYsJO4jqY8S4coK4n2JcAmxIVQ07DmDuI3GbXgOybc1oG9vZiik1G//qiSgsyY1bPTD6KXTsl0/acQoeRaGRjKniz2wOB7VuDn8GGNySc/p7lbxBeCjwvmKE0d96/Jm87ieP+ZFxKAozKyDqNqfIn8/YAjAY3WVDhEuA+W/tJ1o0qCMITCuprxvKQ3r6rkoVO4yhQJmRNOnKDlsAFkuN/D7C7aqGZ/YAu7ARbnYsM9+stEpEzx7AvbtijmvLsuk91zrD5QO9DNOEE3rB+bpeoiRCbRUq2XsvnfbxCmnF2bA0io2RSYPoDgW0soEwtqpB8h6Ltu1KBT7/2AEtqwnYRmF6Bv3nKza/OTERtkaU3SqT6fbKo/425z3/NHfCfSsm6sUT/QccAB3PJQ8MgPq955z55Hk6wRyIWf/1Udyqv1K0tQpaOg+Drb9z89zbXpnKwuV1VNwO3a2yJkH9j5B1RC3Q5NKiU=
  template:
    metadata:
      name: timescaledb-secrets
      namespace: timescaledb
    type: Opaque
