---
# Source: spring-boot-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynchronous-http-server
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: asynchronous-http-server
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: asynchronous-http-server
      app.kubernetes.io/instance: release
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        helm.sh/chart: spring-boot-app-0.0.1
        app.kubernetes.io/name: asynchronous-http-server
        app.kubernetes.io/instance: release
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: spring-projects-registry-secret
      serviceAccountName: asynchronous-http-server
      securityContext:
        {}
      containers:
        - name: asynchronous-http-server
          securityContext:
            {}
          image: "registry.gitlab.notyouraverage.dev/spring-projects/spring-boot-asynchronous-http:82e6e00f"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {}
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: apache-kafka.kafka.svc.cluster.local:9092
            - name: ENABLE_VIRTUAL_THREADS
              value: "true"
            - name: ENABLE_TRACES
              value: "false"
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: TRACES_SAMPLING_RATE
              value: "0.0"
            - name: OLTP_TRACING_ENDPOINT
              value: http://locahost
            - name: KAFKA_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: KAFKA_AUTH_USERNAME
                  name: async-http-server-secrets
            - name: KAFKA_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_AUTH_PASSWORD
                  name: async-http-server-secrets
