---
# Source: spring-boot-app/templates/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: asynchronous-http-server

namespace: spring-projects

resources:
  - sealed-secret.yaml
  - service-account.yaml
  - deployment.yaml
  - service.yaml
patches:
  - path: service-monitor.yaml
    target:
      kind: ServiceMonitor
      name: asynchronous-http-server
