---
# Source: spring-boot-app/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asynchronous-http-server
  labels:
    helm.sh/chart: spring-boot-app-0.0.1
    app.kubernetes.io/name: asynchronous-http-server
    app.kubernetes.io/instance: spring-boot-asynchronous-http
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  namespace: spring-projects
automountServiceAccountToken: true
