kafka:
  defaultStorageClass: longhorn
  replicaCount: 3
  metrics:
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: observability
    prometheusRule:
      enabled: true
      namespace: observability
  volumePermissions:
    enabled: true
  sasl:
    client:
      users:
        - kafka-user
    existingSecret: kafka-credentials
