kafka:
  defaultStorageClass: longhorn
  replicaCount: 3
  metrics:
    jmx:
      enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
    prometheusRule:
      enabled: true
      namespace: monitoring
  volumePermissions:
    enabled: true
  sasl:
    client:
      users:
        - kafka-user
    existingSecret: kafka-credentials
