---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postiz-uploads-pvc
  namespace: postiz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
