---
apiVersion: batch/v1
kind: Job
metadata:
  name: postiz-secret-cleanup
  namespace: postiz
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
    spec:
      serviceAccountName: postiz-secret-cleanup
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting Helm-created secret to allow SealedSecret to take over..."
              kubectl delete secret postiz-postiz-app-secrets -n postiz --ignore-not-found
              echo "Done. SealedSecret controller will recreate the secret."
