---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postiz-secret-cleanup
  namespace: postiz
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postiz-secret-cleanup
  namespace: postiz
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postiz-secret-cleanup
  namespace: postiz
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: postiz-secret-cleanup
    namespace: postiz
roleRef:
  kind: Role
  name: postiz-secret-cleanup
  apiGroup: rbac.authorization.k8s.io
