---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: mixpost-grant
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-mixpost
  privileges:
    - "ALL PRIVILEGES"
  database: mixpost
  table: "*"
  username: mixpost
  host: "%"
  grantOption: false
