sonarqube:
  namespace: sonarqube
  replicaCount: 1
  community:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: cloudflare-tunnel
    hosts:
      - name: sonarqube-k8s.notyouraverage.dev
  prometheusMonitoring:
    podMonitor:
      enabled: true
  monitoringPasscode: sonarqube_monitoring_passcode
